# Generated by Django 4.2.10 on 2025-02-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('app_password', models.CharField(max_length=255)),
                ('imap_server', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.EmailField(blank=True, max_length=254, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('is_checked', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_account.emailaccount')),
            ],
        ),
    ]
