# Generated by Django 4.2.10 on 2025-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='smtp_server',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='smtp_username',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
