# Generated by Django 4.2.10 on 2025-03-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_account', '0002_remove_emailaccount_smtp_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_active',
        ),
    ]
