# Generated by Django 4.2.10 on 2025-03-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_account', '0003_remove_emailaccount_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaccount',
            old_name='is_received',
            new_name='is_active',
        ),
    ]
